models:
  - name: rudder_user_id_stitcher
    model_type: id_stitcher
    model_spec:
      validity_time: 24h # 1 day
      entity_key: user
      edge_sources:
        # Specify from inputs.yaml file
        - from: inputs/rsProductAdded
        - from: inputs/rsOrderCompleted
        - from: inputs/rsCheckoutStepCompleted
  - name: rudder_user_ecommerce_features
    model_type: feature_table_model
    model_spec:
      validity_time: 24h # 1 day
      entity_key: user
      features:
        - last_transaction_value
        - avg_transaction_value
        - avg_units_per_transaction
        - highest_transaction_value
        - median_transaction_value
        - transactions_in_past_90_days
        - days_since_last_purchase
        - total_transactions
        - has_credit_card
        - days_since_first_purchase
        - gross_amt_spent_in_past
        - gross_amt_spent_in_past_30_days
        - gross_amt_spent_in_past_90_days
        - items_purchased_ever
        - days_since_last_cart_add
        - total_products_added
        - carts_in_past_365_days
        - total_carts
        - products_added_in_past_365_days
var_groups:
  - name: user_vars
    entity_key: user
    vars:
      - entity_var:
          name: last_transaction_value
          from: inputs/rsOrderCompleted
          select: first_value(PROPERTIES_REVENUE)
          window:
            order_by:
              - case when PROPERTIES_REVENUE is not null then 2 else 1 end desc
              - timestamp desc
          description: The total value of products that are part of the last transaction.
      - entity_var:
          name: avg_transaction_value
          select: avg( PROPERTIES_REVENUE ::real)
          from: inputs/rsOrderCompleted
          description: Total price in each transaction/Total number of transactions.
      - entity_var:
          name: avg_units_per_transaction
          select: avg(array_size (parse_json( PROPERTIES_PRODUCTS) )::real)
          from: inputs/rsOrderCompleted
          description: It shows the average units purchased in each transaction. (Total units in each transaction/Total transactions). Includes only those transactions where the total price (from column current_total_price) is greater than zero. So, the feature exclude transactions with 100% off, replacement products etc that may result in the total_price being equal to zero.
      - entity_var:
          name: highest_transaction_value
          select: max(PROPERTIES_REVENUE ::real)
          from: inputs/rsOrderCompleted
          description: Of all the transactions done by the user, this features contains the highest transaction value.
      - entity_var:
          name: median_transaction_value
          select: median( PROPERTIES_REVENUE ::real)
          from: inputs/rsOrderCompleted
          description: Median value of total price of all the transactions
      - entity_var:
          name: transactions_in_past_90_days
          select: count(*)::real
          from: inputs/rsOrderCompleted
          where: "{{macro_datediff_n('timestamp','90')}}"
          description: Number of transactions in last 90 day
      - entity_var:
          name: max_timestamp_order_created
          select: max(timestamp)
          from: inputs/rsOrderCompleted
          is_feature: false
      - entity_var:
          name: days_since_last_purchase
          select: "{{macro_datediff('max_timestamp_order_created')}}"
      - entity_var:
          name: total_transactions
          select: count(*)
          from: inputs/rsOrderCompleted
          description: Total number of transactions done by the user
      - entity_var:
          name: has_credit_card
          select: max(case when lower(PROPERTIES_PAYMENT_METHOD) in ('visa','american express','mastercard') then 1 else 0 end)
          from: inputs/rsCheckoutStepCompleted
      - entity_var:
          name: min_timestamp_order_created
          select: min(timestamp)
          from: inputs/rsOrderCompleted
          is_feature: false
      - entity_var:
          name: days_since_first_purchase
          select: "{{macro_datediff('min_timestamp_order_created')}}"
          description: Number of days since the user purchased the first product
      - entity_var:
          name: gross_amt_spent_in_past
          select: sum(PROPERTIES_REVENUE::real)
          from: inputs/rsOrderCompleted
          description: Total value of products purchased till date.
      - entity_var:
          name: gross_amt_spent_in_past_30_days
          select: sum(PROPERTIES_REVENUE::real)
          from: inputs/rsOrderCompleted
          where: "{{macro_datediff_n('timestamp','30')}}"
          description: Total value of products purchased till date.
      - entity_var:
          name: gross_amt_spent_in_past_90_days
          select: sum(PROPERTIES_REVENUE::real)
          from: inputs/rsOrderCompleted
          where: "{{macro_datediff_n('timestamp','90')}}"
          description: Total value of products purchased till date.
      - entity_var:
          name: items_purchased_ever
          select: array_agg(SKU)
          from: models/rsItemsPurchasedEver
          description: The list of unique products bought by the user.
      - entity_var:
          name: carts_in_past_365_days
          select: count(distinct PROPERTIES_CART_ID)
          from: inputs/rsProductAdded
          where: "{{macro_datediff_n('timestamp','365')}}"
          description: A cart id is created for events such as create_cart,update_cart. This coln specifies how many cart ids were created in the past 365 days
      - entity_var:
          name: total_carts
          select: count(distinct PROPERTIES_CART_ID)
          from: inputs/rsProductAdded
          description: Total carts created by the user till date.
      - entity_var:
          name: products_added_in_past_365_days
          select: array_agg(distinct PROPERTIES_PRODUCT_ID)
          from: inputs/rsProductAdded
          where: "{{macro_datediff_n('timestamp','365')}}"
          description: List of products added to cart by the user in last 7 days. (array with list of all product ids). It includes all purchased products plus current active cart.
      - entity_var:
          name: total_products_added
          select: array_agg(distinct PROPERTIES_PRODUCT_ID)
          from: inputs/rsProductAdded
          description: Total products added to cart till date. (array with list of all product ids). It includes all purchased products plus current active cart.
      - entity_var:
          name: max_timestamp_product_added
          select: max(timestamp)
          from: inputs/rsProductAdded
          is_feature: false
      - entity_var:
          name: days_since_last_cart_add
          select: "{{macro_datediff('max_timestamp_product_added')}}"
          description: Number of days since the user has added a product to cart
